---
- hosts: 172.31.38.38
  become: yes
  tasks:
  - name: install tree 
    apt:
     name: tree 
     state: present 
  - name: install git 
    apt: 
     name: git 
     state: 
      
  - name: install wget 
    apt:
     name: wget 
     state: present 

    
    