---
- hosts: 172.31.38.38
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: install webserver
    apt:
     name: apache2
     state: present
    notify: restartwebserver  
  - name: i want to copy static files into ansible nodes side 
    copy:
       src: mystaticfile.html
       dest: /var/www/html/index.html 
  - name: i want to copy dynamic files into ansible nodes
    template:
        src: myindex.j2
        dest: /var/www/html/index.html 
    notify: restartwebserver     
  - name: i want to download files from remote (internet) into node side 
    get_url:
        url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
        dest: /home/ubuntu/jenkins.war
        force_basic_auth: yes   

  handler:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted               