---
- hosts: 172.31.38.38
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: install webserver
    apt:
     name: apache2
     state: present 
  - name: i want to copy static files into ansible nodes side 
    template:
       src: mystaticfile.html
       dest: /var/www/html/index.html   