---
-  name: copy tomcat user xml file into node side 
   template:
      src: template/tomuser.j2
      dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy tomcat context xml file into nodes
  template:
      src: template/tomcontext.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy tomcat host context xml file into nodes
  template:
     src: template/hostcontext.j2
     dest:  /opt/tomcat/webapps/host-manager/META-INF/context.xml


